<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [2]:
import numpy as np

array_unidimensional = np.arange(0,10)
array_unidimensional

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [3]:
array_unidimensional.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [4]:
array_unidimensional = np.array([0, 2, 0, 3, 0, 4, 0])
np.where(array_unidimensional != 0)

(array([1, 3, 5]),)

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [5]:
array_tridimensional = np.random.randint(0, 2, (3, 3))
array_tridimensional

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int32)

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [6]:
array = np.random.random(10)
print(f"El valor mínimo es: {array.min()}")
print(f"El valor máximo es: {array.max()}")

El valor mínimo es: 0.11096240679539848
El valor máximo es: 0.9835127475818444


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [7]:
array = np.random.randint(10)
np.transpose(array)

array(6)


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [8]:
array_tridimensional = np.random.randint(1, 25, (2,3,4))
print(f"Array generado:\n{array_tridimensional}\n")
print(f"Primer 15 del array: {array_tridimensional[array_tridimensional == 15][0]}\n")
print(f"Todos los elementos del primer array: {array_tridimensional[0]}\n")
print(f"Última fila del último array: {array_tridimensional[-1][-1]}\n")

Array generado:
[[[ 4 13  9 13]
  [ 6  5  6 17]
  [15 10 18 10]]

 [[ 4 20 22 19]
  [10  8 13  8]
  [12 19  1  8]]]

Primer 15 del array: 15

Todos los elementos del primer array: [[ 4 13  9 13]
 [ 6  5  6 17]
 [15 10 18 10]]

Última fila del último array: [12 19  1  8]




#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [9]:
array_tridimensional = np.random.randint(1, 31, (3,2,5))
print(f"Array generado:\n{array_tridimensional}\n")
print(f"Los 2 primeros elementos de cada fila: {array_tridimensional[:,:,0:2]}\n")
print(f"Todas las filas de los 2 ultimos arrays: {array_tridimensional[-2:]}\n")

Array generado:
[[[14 27  3 11 15]
  [24  7 30  4 30]]

 [[14 25 17  1  9]
  [ 3 19 14 23  6]]

 [[10 12 23 10 26]
  [17 22 16 21 22]]]

Los 2 primeros elementos de cada fila: [[[14 27]
  [24  7]]

 [[14 25]
  [ 3 19]]

 [[10 12]
  [17 22]]]

Todas las filas de los 2 ultimos arrays: [[[14 25 17  1  9]
  [ 3 19 14 23  6]]

 [[10 12 23 10 26]
  [17 22 16 21 22]]]



#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [10]:
array_tridimensional = np.random.randint(1, 25, (4,3,2))
print(f"Array generado:\n{array_tridimensional}\n")
array_tridimensional[1,1,:] = np.zeros_like(array_tridimensional[1,1,:])
print(f"Cambiar todos los elementos de la 2ª fila del segundo array por 0:\n {array_tridimensional[1,1,:]}\n")
array_tridimensional[-1,:] = np.ones_like(array_tridimensional[-1,:])*-1
print(f"Todos los valores del último array a -1:\n {array_tridimensional[-1]}\n")

Array generado:
[[[ 9  4]
  [18  8]
  [17  8]]

 [[ 9 10]
  [14 19]
  [ 9 12]]

 [[16  1]
  [ 6  3]
  [ 1  7]]

 [[13 11]
  [11 12]
  [15 20]]]

Cambiar todos los elementos de la 2ª fila del segundo array por 0:
 [0 0]

Todos los valores del último array a -1:
 [[-1 -1]
 [-1 -1]
 [-1 -1]]




#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [11]:
array_tridimensional = np.random.randint(-10, 14, (2,4,3))
print(f"Array generado:\n{array_tridimensional}\n")
print(f"Todos los elementos mayores a 5:\n {array_tridimensional[array_tridimensional > 5]}\n")
array_tridimensional[array_tridimensional < 0] = 0
print(f"Reemplaza todos los elementos negativos por 0:\n {array_tridimensional}\n")

Array generado:
[[[-2  2 -4]
  [ 4  6 -4]
  [11 13 13]
  [ 8  9  2]]

 [[10 10  8]
  [ 7 -4  8]
  [ 2 -6 -3]
  [ 2  3 -2]]]

Todos los elementos mayores a 5:
 [ 6 11 13 13  8  9 10 10  8  7  8]

Reemplaza todos los elementos negativos por 0:
 [[[ 0  2  0]
  [ 4  6  0]
  [11 13 13]
  [ 8  9  2]]

 [[10 10  8]
  [ 7  0  8]
  [ 2  0  0]
  [ 2  3  0]]]



#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [12]:
array_tridimensional = np.random.randint(1, 28, (3,3,3))
print(f"Array generado:\n{array_tridimensional}\n")
print(f"Subarray del segundo array que contenga solo las dos primeras columnas:\n {array_tridimensional[1,:,:2][0]}\n")
array_tridimensional[array_tridimensional < 0] = 0
print(f"Selecciona todos los elementos del tercer array que son mayores que 20:\n {array_tridimensional[-1][array_tridimensional[2, :,:]>20]}\n")

Array generado:
[[[21  3 18]
  [21  3 18]
  [18 24 18]]

 [[25 24 16]
  [10  6 11]
  [ 5 19 13]]

 [[17 18 17]
  [17 11  4]
  [ 5 27 17]]]

Subarray del segundo array que contenga solo las dos primeras columnas:
 [25 24]

Selecciona todos los elementos del tercer array que son mayores que 20:
 [27]



#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [13]:
array = np.random.randint(1, 20, 10)
print(array)
indice_max = np.where(array == array.max())
indice_min = np.where(array == array.min())
array[indice_max] = 0
array[indice_min] = 0
print(array)

[15  3  3 13 11 17  7  2 19 10]
[15  3  3 13 11 17  7  0  0 10]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [14]:
array = np.random.randint(1, 100, 15)
print(np.sort(array))

[ 9  9 24 33 34 44 49 59 61 67 75 78 78 84 86]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [15]:
array = np.random.randint(1, 10, (4,4))
print(array)
print(f"Suma filas: {np.sum(array,1)}")
print(f"Suma columnas: {np.sum(array,0)}")

[[7 4 3 6]
 [3 8 6 8]
 [2 6 7 3]
 [2 6 4 8]]
Suma filas: [20 25 18 20]
Suma columnas: [14 24 20 25]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [16]:
array = np.ones((5, 5), dtype=int)
array[1:-1, 1:-1] = 0
print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [17]:
array = np.random.randint(1, 10, 10)
media = np.mean(array)
desviacion_estandar = np.std(array)
print("La media es:", media)
print("La desviación estandar es:", desviacion_estandar)

La media es: 5.7
La desviación estandar es: 2.4919871588754225


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [18]:
array_tridimensional = np.random.randint(1, 25, (2, 3, 4))
print(array_tridimensional)
array_tridimensional = np.transpose(array_tridimensional)
print("\n",array_tridimensional)

[[[24 18  9 23]
  [16 18 20  6]
  [17  3 16  3]]

 [[ 6  7  4 10]
  [16  2 10 24]
  [ 9 10 20 22]]]

 [[[24  6]
  [16 16]
  [17  9]]

 [[18  7]
  [18  2]
  [ 3 10]]

 [[ 9  4]
  [20 10]
  [16 20]]

 [[23 10]
  [ 6 24]
  [ 3 22]]]


Respuesta al ejercicio 14.b:

Lo que ha ocurrido es que al transponer se ha cambiado las **columnas** por el **número de arrays**, las **filas se mantienen** y los **arrays** que habían por las **columnas**

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [19]:
array_tridimensional = np.random.randint(1, 25, (3, 4, 2))
array_tridimensional = np.transpose(array_tridimensional, (1, 0, 2))
array_tridimensional

array([[[ 8,  5],
        [ 3, 11],
        [ 5,  8]],

       [[24, 24],
        [16, 12],
        [12, 12]],

       [[ 1, 16],
        [18, 10],
        [17, 17]],

       [[ 8,  2],
        [15, 19],
        [15,  2]]], dtype=int32)

#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [20]:
array_tridimensional = np.random.randint(1, 25, (3, 2, 4))
array_tridimensional = np.swapaxes(array_tridimensional, 0, 2)
array_tridimensional = np.swapaxes(array_tridimensional, 1, 2)
array_tridimensional

array([[[10, 12],
        [18, 22],
        [ 1,  7]],

       [[ 5,  9],
        [23, 12],
        [18,  6]],

       [[ 1,  3],
        [ 8,  5],
        [13, 12]],

       [[19, 23],
        [17, 14],
        [18, 24]]], dtype=int32)

#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [107]:
array_tridimensional = np.random.randint(-10, 11, (3, 4, 5))
array = np.empty(array_tridimensional.shape, dtype=str)
indice_media = np.where(array == array.mean())
array[indice_media] = "M"

TypeError: the resolved dtypes are not compatible with add.reduce. Resolved (dtype('<U1'), dtype('<U1'), dtype('<U2'))

#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [106]:
array = np.random.randint(1, 4, (4,4))
print(array, "\n")

iguales = False
coincidencia = False
for n in range(array.shape[0]):
    for i in range(array.shape[1]):
        iguales = True
        for j in range(array.shape[1]):
            if array[n][j] != array[j][i]:
                iguales = False
                break
        if iguales == True:
            coincidencia = True
            print(f"La fila {i} es igual a la columna {j}")
if coincidencia == False:
    print(f"No hay ninguna fila igual a la columna")

[[2 3 2 2]
 [2 2 2 2]
 [2 3 2 2]
 [3 2 2 3]] 

La fila 2 es igual a la columna 3
